// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.1
// source: restoration.proto

package pbg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestorationCollectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File           string            `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Level          string            `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	CallTime       int64             `protobuf:"varint,3,opt,name=call_time,json=callTime,proto3" json:"call_time,omitempty"`
	Service        string            `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	TraceId        string            `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Message        string            `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Data           []byte            `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	Extra          map[string][]byte `protobuf:"bytes,8,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Identification string            `protobuf:"bytes,9,opt,name=identification,proto3" json:"identification,omitempty"`
}

func (x *RestorationCollectionRequest) Reset() {
	*x = RestorationCollectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restoration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestorationCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestorationCollectionRequest) ProtoMessage() {}

func (x *RestorationCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restoration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestorationCollectionRequest.ProtoReflect.Descriptor instead.
func (*RestorationCollectionRequest) Descriptor() ([]byte, []int) {
	return file_restoration_proto_rawDescGZIP(), []int{0}
}

func (x *RestorationCollectionRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *RestorationCollectionRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *RestorationCollectionRequest) GetCallTime() int64 {
	if x != nil {
		return x.CallTime
	}
	return 0
}

func (x *RestorationCollectionRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *RestorationCollectionRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RestorationCollectionRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RestorationCollectionRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RestorationCollectionRequest) GetExtra() map[string][]byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *RestorationCollectionRequest) GetIdentification() string {
	if x != nil {
		return x.Identification
	}
	return ""
}

type RestorationCollectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RestorationCollectionResponse) Reset() {
	*x = RestorationCollectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restoration_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestorationCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestorationCollectionResponse) ProtoMessage() {}

func (x *RestorationCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restoration_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestorationCollectionResponse.ProtoReflect.Descriptor instead.
func (*RestorationCollectionResponse) Descriptor() ([]byte, []int) {
	return file_restoration_proto_rawDescGZIP(), []int{1}
}

var File_restoration_proto protoreflect.FileDescriptor

var file_restoration_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xea, 0x02, 0x0a, 0x1c, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1b,
	0x0a, 0x09, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x3e,
	0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e,
	0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x78, 0x74,
	0x72, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x12, 0x26,
	0x0a, 0x0e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x38, 0x0a, 0x0a, 0x45, 0x78, 0x74, 0x72, 0x61, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x1f, 0x0a, 0x1d, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0x6c, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x56, 0x0a, 0x15, 0x52, 0x65, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1d, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x70, 0x62, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_restoration_proto_rawDescOnce sync.Once
	file_restoration_proto_rawDescData = file_restoration_proto_rawDesc
)

func file_restoration_proto_rawDescGZIP() []byte {
	file_restoration_proto_rawDescOnce.Do(func() {
		file_restoration_proto_rawDescData = protoimpl.X.CompressGZIP(file_restoration_proto_rawDescData)
	})
	return file_restoration_proto_rawDescData
}

var file_restoration_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_restoration_proto_goTypes = []interface{}{
	(*RestorationCollectionRequest)(nil),  // 0: RestorationCollectionRequest
	(*RestorationCollectionResponse)(nil), // 1: RestorationCollectionResponse
	nil,                                   // 2: RestorationCollectionRequest.ExtraEntry
}
var file_restoration_proto_depIdxs = []int32{
	2, // 0: RestorationCollectionRequest.extra:type_name -> RestorationCollectionRequest.ExtraEntry
	0, // 1: RestorationService.RestorationCollection:input_type -> RestorationCollectionRequest
	1, // 2: RestorationService.RestorationCollection:output_type -> RestorationCollectionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_restoration_proto_init() }
func file_restoration_proto_init() {
	if File_restoration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_restoration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestorationCollectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restoration_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestorationCollectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_restoration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_restoration_proto_goTypes,
		DependencyIndexes: file_restoration_proto_depIdxs,
		MessageInfos:      file_restoration_proto_msgTypes,
	}.Build()
	File_restoration_proto = out.File
	file_restoration_proto_rawDesc = nil
	file_restoration_proto_goTypes = nil
	file_restoration_proto_depIdxs = nil
}
