name: Docker Build and Push

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: tag_name
        run: echo "::set-output name=TAG_NAME::$(echo ${GITHUB_REF/refs\/tags\//})"
        if: startsWith(github.ref, 'refs/tags/')

      - name: Build and push (with tag)
        uses: docker/build-push-action@v3
        if: steps.tag_name.outputs.TAG_NAME != ''
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: |
            ghcr.io/alioth-center/restoration:${{ steps.tag_name.outputs.TAG_NAME || 'dev' }}
            ghcr.io/alioth-center/restoration:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            LOG_FILE=${{ env.LOG_FILE }}

      - name: Build and push (no tag)
        if: steps.tag_name.outputs.TAG_NAME == ''
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ghcr.io/alioth-center/restoration:dev
          platforms: linux/amd64,linux/arm64
